DEV_TYPE_CONTROLLER = 0
DEV_TYPE_BATTERTY = 1

MSG_CNT_STATE = 0
MSG_CNT_TEMPS = 1
MSG_CNT_RPM = 2
MSG_CNT_CURRENTS = 3
MSG_CNT_RESETFLAGS = 4
MSG_CNT_ANGCAL = 5
MSG_CNT_PID_D = 6
MSG_CNT_PID_Q = 7
MSG_CNT_MOT_PARAM = 8
MSG_CNT_ACC_DEC = 9
MSG_CNT_CONF_CAN = 10


class CanDevice:
    pass
